name: Publish Release on Push to Main

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Create Release Tag
        id: create_tag
        run: |
          # Generate a version number based on current timestamp or commit hash
          VERSION="v$(date +'%Y%m%d%H%M%S')"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          git tag -a $VERSION -m "Automated release for commit $GITHUB_SHA"
          git push origin $VERSION

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          release_name: "Automated Release ${{ env.VERSION }}"
          body: "Automated release for commit ${{ github.sha }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}